### PR TITLE
Merge user mask and model updates into refactor_code branch

### PR DESCRIPTION
**Pull request by psheehan**
@jjtobin, this PR is to merge your updates for specifying a user-provided mask and or model into the refactor_code branch. Rather than merge straight into refactor_code, I thought it would make sense to put into a separate branch and open a PR to test on and discuss a few things.

A few items:

- I think I merged everything correctly, but if you are able to look it over to make sure that it seems like all is in the right place (or to test it to make sure it is doing the right thing), that would be helpful.
- I'd like to follow the principles of the refactor_code branch and store the usermodel and usermask info in the selfcal_library so that the tclean_wrapper (and usermodel_wrapper) codes can mostly handle that under-the-hood. I still need to do that.
- To that point - I see that usermodel and usermask are specified per-target but not per-band. Is there a motivation for that? I might suggest making it per-target per-band and then we can cleanly put the model into the selfcal_library and reference it from there when needed?

(Part of the reason I'm making this PR is to have some record of what I'm thinking about before the weekend. I'd say it's not ready to merge yet...)

### CODE REVIEW

**Comment by jjtobin** [comment]
There is no reason to not add the per-band specificity to the usermask and model, I simply hadn't thought that far ahead prior to implementing. I don't have any problem with adding this to the selfcal_library or plan within the refactor_code branch.

**Comment by psheehan** [comment]
Ok great, I'll go ahead and do that for the refactor_code branch and push that here

**Comment by psheehan** [comment]
Ok, I've updated the branch to now store the usermask and usermodel in the selfcal_library and tclean_wrapper to know what to do with them so we don't need to pass them around all over the place. A few notes:

- For the mask, I (think I) have added logic so that if we call `tclean_wrapper` with the `mask` keyword set, that will override anything. Then it falls back to `selfcal_library[target][band]['usermask']` if available, otherwise auto-multithresh.
- For the model, I think the only reason `tclean_wrapper` needed to know about `usermodel` was to not save the model if we were telling it to save the model. There were a bunch of `tclean_wrapper` calls in `auto_selfcal.py` that specified `usermodel=''`, but I *believe* that as I have it set up now those aren't necessary because those `tclean_wrapper` calls also explicitly set `savemodel='none'`. But let me know if I've got any of this wrong... because now that I look at it, I'm not sure where we specify to `tclean` to use the existing MODEL column....

If you are able to look this all over that would be helpful. I also haven't done any actual testing of this, either... so probably would be good to make sure this is all working properly before we actually merge.

**Comment by psheehan** [comment]
As a note, this PR now includes all more recent changes from  @jjtobin's main, including the changes from this PR: https://github.com/jjtobin/auto_selfcal/pull/37

**Pull request merged**
